name: Automatic semantic versioning
on:
  workflow_dispatch:
  push:
    branches: [main, develop, alpha, beta]

jobs:
  versioning:
    name: Semantic versioning
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      checks: write # to be able to override branch protection requirements
      pull-requests: write # to be able to comment on released pull requests
    timeout-minutes: 15
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

    outputs:
      new-release-published: ${{ steps.get-next-version.outputs.new-release-published }}
      new-release-version: ${{ steps.get-next-version.outputs.new-release-version }}
      new-release-git-tag: ${{ steps.get-next-version.outputs.new-release-git-tag }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: yarn

      - name: Install plugins
        run: yarn add -D @semantic-release/changelog @semantic-release/git @semantic-release/exec -W
      
      - name: Print current version
        id: current_version
        run: echo "CURRENT_VERSION=$(jq -r ".version" ./package.json)" >> $GITHUB_OUTPUT;

      - name: Run semantic release
        id: get-next-version
        run: yarn semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  print:
    runs-on: ubuntu-latest
    needs: versioning
    if: needs.versioning.outputs.new-release-published == 'true'
    steps:
      - name: Print version numbers
        run: |
          echo "The new release version is ${{ needs.versioning.outputs.new-release-version }}"
          echo "The new release version is ${{ needs.versioning.outputs.new-release-git-tag }}"
